### ISSUE TITLE
UPGRADE documentation only updated to MRBS 1.8.0

### ISSUE THREAD

**Issue by jasper2virtual** [meeting-room-booking-system/mrbs-web#1]
Hello, we are using the MRBS at 1.7.3, and we love it.
We would like to upgrade to MRBS 1.10.0, but cannot find any upgrade guide.
May I know will you update the UPGRADE to include 1.10.0, or else we will find out the procedure ourselves and contribute it later.

**Comment by jberanek** [comment]
Apologies, I completely missed this issue. The UPGRADE guide only mentions specific releases if they have breaking changes for existing configuration. Otherwise the generic upgrade guide under "Upgrade Information for previous releases of MRBS" will always work.
